# Generated by Django 4.1.7 on 2023-06-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.transactioncategory')),
            ],
        ),
    ]
