# Generated by Django 4.1.7 on 2023-06-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Married',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married_date', models.DateField(null=True)),
                ('divorced_date', models.DateField(null=True)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('dod', models.DateField(null=True)),
                ('note', models.CharField(max_length=200)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.gender')),
                ('parent_marriage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='familytree.married')),
            ],
        ),
        migrations.AddField(
            model_name='married',
            name='person_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_person_one', to='familytree.person'),
        ),
        migrations.AddField(
            model_name='married',
            name='person_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_person_two', to='familytree.person'),
        ),
    ]
