# Generated by Django 4.1.7 on 2023-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='married',
            name='divorced_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='married',
            name='married_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='married',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
