# Generated by Django 4.1.7 on 2023-06-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_alter_married_divorced_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parent_marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='familytree.married'),
        ),
    ]
